info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: DEBUG
    org.springframework: ERROR
  profile: NON_JSON

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: info, health
  endpoint:
    info:
      enabled: true 
    health:
      enabled: true

server:
  port: 8161
  undertow:
    threads:
      worker: 50
      io: 50

spring:
  mvc:
    servlet:
      path: /

  #  security:
  #    user:
  #      name: serco_cks
  #      password: temporary
  output:
    ansi:
      enabled: never
  application:
    name: ONS SDC MockCaseService

