apiVersion: v1
kind: Service
metadata:
  name: mock-case
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"http":"mock-case-ingress"}}'
  labels:
    app: mock-case
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http-server
  selector:
    app: mock-case
