apiVersion: v1
kind: Service
metadata:
  name: mockcaseapi
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"http":"mockcaseapiingress"}}'
  labels:
    app: mockcaseapi
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http-server
  selector:
    app: mockcaseapi
